:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+AUTHOR: Marcio Woitek
#+TITLE: Capstone Case Questions
#+LATEX_HEADER: \usepackage[a4paper,left=1cm,right=1cm,top=1cm,bottom=1cm]{geometry}
#+LATEX_HEADER: \usepackage[american]{babel}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[sc]{mathpazo}
#+LATEX_HEADER: \linespread{1.05}
#+LATEX_HEADER: \renewcommand{\labelitemi}{$\rhd$}
#+LATEX_HEADER: \setlength\parindent{0pt}
#+LATEX_HEADER: \setlist[itemize]{leftmargin=*}
#+LATEX_HEADER: \setlist{nosep}
#+OPTIONS: ':t
#+OPTIONS: author:nil
#+OPTIONS: date:nil
#+OPTIONS: title:nil
#+OPTIONS: toc:nil
#+STARTUP: hideblocks

#+BEGIN_SRC latex
\thispagestyle{empty}
\pagestyle{empty}
#+END_SRC

* Problem 1

*Answer:* 4.5\\

This value is given in the background text: "Sunrise currently pays about 4.5%
on their debt, and that rate is not expected to change with the additional
purchase of the oven."

* Problem 2

*Answer:* 7.4\\

To determine the cost of equity, we need a few values given in the background
text. The relevant part is the following:
#+BEGIN_QUOTE
In researching similar large public bakery and other food manufacturers, she
found that firms in her industry with about the same level of risk mostly had
stock market betas around 0.80 on average. She also noted that many analysts
used a ballpark equity risk premium of 5.5% and a current yield on U.S. treasury
bonds (risk-free rate) of about 3%.
#+END_QUOTE
Summarizing:
- the risk-free rate is \( r_{\mathrm{RF}}=0.03 \);
- the company's beta is \( \beta=0.8 \);
- the equity premium is \( \mathrm{EP}=0.055 \).
Recall that the cost of equity \( R_e \) can be computed as follows:
\begin{equation}
R_e=r_{\mathrm{RF}}+\beta\cdot\mathrm{EP}.
\end{equation}
By substituting the known values into the RHS of the above equation, we get
#+NAME: problem_2
#+BEGIN_SRC python :results output :exports none
rfr = 3 / 100
beta = 0.8
ep = 5.5 / 100
re = rfr + beta * ep
print(round(re, 3))
print(f"{round(100 * re, 1)}%")
#+END_SRC
#+RESULTS: problem_2
: 0.074
: 7.4%
\begin{align}
  \begin{split}
    R_e&=r_{\mathrm{RF}}+\beta\cdot\mathrm{EP}\\
    &=0.03+0.8\cdot 0.055\\
    &=0.074.
  \end{split}
\end{align}
Therefore, the cost of equity is 7.4%.

* Problem 3

*Answer:* 6.3375\\

To answer this question, we need more data found in the background text.
Specifically, we need the tax rate. This value is given in the following
sentence: "Sunrise has a corporate tax rate of 30%." Another relevant part of
the background text is
#+BEGIN_QUOTE
Currently, Sunrise maintains a rough capital structure of about 25% debt and 75%
equity. (...) Overall, the cash purchase of the oven is not expected to change
the capital structure of the Sunrise Corporation.
#+END_QUOTE
Next, we summarize the data we'll use to solve this problem. If we denote the
value of the assets by \( A \), then we have the following:
- equity is \( E=0.75 A \);
- debt is \( D=0.25 A \);
- cost of equity is \( R_e=0.074 \);
- cost of debt is \( R_d=0.045 \);
- tax rate is \( t=0.3 \).
To continue, recall that the WACC is given by
\begin{equation}
\mathrm{WACC}=\frac{E}{E+D}R_e+\frac{D}{E+D}(1-t)R_d.
\end{equation}
By substituting the known values into the RHS of this equation, we get
#+NAME: problem_3
#+BEGIN_SRC python :results output :exports none
wacc = 0.75 * 0.074 + 0.25 * 0.7 * 0.045
print(round(wacc, 6))
print(f"{round(100 * wacc, 4)}%")
#+END_SRC
#+RESULTS: problem_3
: 0.063375
: 6.3375%
\begin{align}
  \begin{split}
    \mathrm{WACC}&=\frac{E}{E+D}R_e+\frac{D}{E+D}(1-t)R_d\\
    &=\frac{0.75 A}{0.75 A+0.25 A}R_e+\frac{0.25 A}{0.75 A+0.25 A}(1-t)R_d\\
    &=0.75R_e+0.25(1-t)R_d\\
    &=0.75\cdot 0.074+0.25\cdot(1-0.3)\cdot 0.045\\
    &=0.75\cdot 0.074+0.25\cdot 0.7\cdot 0.045\\
    &=0.063375.
  \end{split}
\end{align}
Therefore, as a percentage, the WACC is 6.3375%.

* Problem 4

*Answer:* 6.3375\\

To evaluate the feasibility of the oven purchase, we should use the WACC. Then
the answer to this question is the same as the previous one.

* Problem 5

*Answer:* 35000\\

There's nothing to compute. The annual depreciation expense can be found in the
income statement we were given. The corresponding value is $35,000.

* Problem 6

*Answer:* Row A\\

Once again, there's nothing to compute. The answer corresponds to the last line
of the income statement.

* Problem 7

*Answer:* Row B\\

In this case, the working capital is computed as the difference between the
non-cash current assets [Other Current Assets (Inventory/Receivables)] and the
current liabilities [Current Liabilities (Payables)]. After calculating the
working capital, we can determine its changes by subtracting consecutive values.
However, we need to pay special attention to the first and last changes. The
background text explains what the first change should be:
#+BEGIN_QUOTE
Operation of the oven also requires a small initial investment in an inventory
of spare parts of $15,000. (...) The investment in inventory represents an
increase in other current assets (inventory) that should be included as a change
in working capital requirements for Sunrise Bakery.
#+END_QUOTE
In the same paragraph, the value for the last change is also explained:
#+BEGIN_QUOTE
At the end of the project, Erica expects to recover all of the working capital
invested in the project. In other words, she expects a cash flow equal to the
amount of Non-Cash Current Assets less Current Liabilities in the last year of
the project.
#+END_QUOTE
By using the above information, we can construct the following table:
#+NAME: problem_7
#+BEGIN_SRC python :results value table :hlines no :exports none
ans_7 = [
    ["", "0", "1", "2", "3", "4", "5", "6"],
    [
        "Other Current Assets (Inventory/Receivables)",
        "$15,000",
        "$17,025",
        "$17,175",
        "$17,325",
        "$17,475",
        "$17,475",
        "$17,475",
    ],
    ["Current Liabilities (Payables)", "$0", "$2,700", "$2,900", "$3,100", "$3,300", "$3,300", "$3,300"],
    ["Working Capital", "$15,000", "$14,325", "$14,275", "$14,225", "$14,175", "$14,175", "$14,175"],
    ["Change in Working Capital", "$15,000", "-$675", "-$50", "-$50", "-$50", "$0", "-$14,175"],
]
return ans_7
#+END_SRC
#+RESULTS: problem_7
|                                              | 0       | 1       | 2       | 3       | 4       | 5       | 6        |
| Other Current Assets (Inventory/Receivables) | $15,000 | $17,025 | $17,175 | $17,325 | $17,475 | $17,475 | $17,475  |
| Current Liabilities (Payables)               | $0      | $2,700  | $2,900  | $3,100  | $3,300  | $3,300  | $3,300   |
| Working Capital                              | $15,000 | $14,325 | $14,275 | $14,225 | $14,175 | $14,175 | $14,175  |
| Change in Working Capital                    | $15,000 | -$675   | -$50    | -$50    | -$50    | $0      | -$14,175 |
#+LATEX: {\small
#+ATTR_LATEX: :align |l|c|c|c|c|c|c|c|
|----------------------------------------------+---------+---------+---------+---------+---------+---------+----------|
|                                              | 0       | 1       | 2       | 3       | 4       | 5       | 6        |
|----------------------------------------------+---------+---------+---------+---------+---------+---------+----------|
| Other Current Assets (Inventory/Receivables) | $15,000 | $17,025 | $17,175 | $17,325 | $17,475 | $17,475 | $17,475  |
| Current Liabilities (Payables)               | $0      | $2,700  | $2,900  | $3,100  | $3,300  | $3,300  | $3,300   |
| Working Capital                              | $15,000 | $14,325 | $14,275 | $14,225 | $14,175 | $14,175 | $14,175  |
| Change in Working Capital                    | $15,000 | -$675   | -$50    | -$50    | -$50    | $0      | -$14,175 |
|----------------------------------------------+---------+---------+---------+---------+---------+---------+----------|
#+LATEX: }
Notice that the last row is identical to Row B. This is the correct answer.

* Problem 8

*Answer:* 140000\\

Once again, there's nothing that we need to compute. In this case, the terminal
value corresponds to the value of the oven after six years. This amount is given
to us in the background text. The relevant part is
#+BEGIN_QUOTE
After six years, Erica's sales representative expects the oven to be worth about
$140,000, which is just equal to the accounting book value of the oven after six
years of accumulated depreciation (...).
#+END_QUOTE
Then the answer is clearly $140,000.

* Problem 9

*Answer:* Row D\\

First, recall how to calculate the free cash flow. We start from the net income,
which is given in the income statement [Profit after tax (Net Income)]. Then we
do the following:
- subtract the increase in working capital;
- add the depreciation back;
- subtract the capital expenditure; and
- add the salvage value.
We already know the changes in working capital. These amounts were computed when
we solved Problem 7. We also know the depreciation values. They can be found in
the income statement. Moreover, we know that the capital expenditure is non-zero
only for period 0. This amount corresponds to the price of the oven, $350,000.
Finally, as discussed in the solution to the previous problem, we have the
salvage value: $140,000. This amount contributes to the free cash flow only in
the last period. Therefore, we already have all the data we need to determine
the free cash flows. By performing the calculations described above, we get the
following result:
#+NAME: problem_9
#+BEGIN_SRC python :results value table :hlines no :exports none
ans_9 = [
    ["0", "1", "2", "3", "4", "5", "6"],
    ["-$365,000", "$91,675", "$96,650", "$102,250", "$107,850", "$107,800", "$261,975"],
]
return ans_9
#+END_SRC
#+RESULTS: problem_9
|         0 |       1 |       2 |        3 |        4 |        5 |        6 |
| -$365,000 | $91,675 | $96,650 | $102,250 | $107,850 | $107,800 | $261,975 |
#+ATTR_LATEX: :align |c|c|c|c|c|c|c|
|-----------+---------+---------+----------+----------+----------+----------|
|         0 |       1 |       2 |        3 |        4 |        5 |        6 |
|-----------+---------+---------+----------+----------+----------+----------|
| -$365,000 | $91,675 | $96,650 | $102,250 | $107,850 | $107,800 | $261,975 |
|-----------+---------+---------+----------+----------+----------+----------|
Notice that the last row is identical to Row D. This is the correct answer.

* Problem 10

*Answer:* 21.942182380796513\\

I wrote a Python function to help me compute the IRR. So I'm not going to
explain the solution to this problem in a detailed manner. It's possible to show
that the IRR is the only positive number \( x \) that satisfies the equation
\begin{equation}
14600 x^6 + 83933 x^5 + 196799 x^4 + 235776 x^3 + 142550 x^2 + 28591 x - 16128 = 0.
\end{equation}
A very close approximation for this root is \( x\approx 0.21942182380796513 \).
As a percentage, this value can be written as 21.942182380796513%. Probably,
this level of precision isn't required. However, I'm not sure about the number
of decimal places I should include. Then I decided to include as many as I can.

* Problem 11

*Answer:* 236546\\

Once again, I implemented a Python function to solve the problem. All this
function does is to apply the definition of NPV. We know the value of the
initial investment, and we've computed the cash flow for each of the six years.
We've also determined the discount rate to be used, which is equal to the WACC.
So it's really just a matter of substituting values into a formula. By doing so,
we obtain a net present value of $236,546.

* Problem 12

*Answer:* 4\\

To answer this question, all we need to do is to accumulate the free cash flows
until the result becomes greater than or equal to the initial investment. To do
so, I wrote a simple Python loop. The value I got is 4. Therefore, it takes 4
years to pay off the investment.

* Problem 13

*Answer:* 27.42857142857143\\

To determine the return on invested capital, we need two averages. Specifically,
we have to know
- the mean net income, and
- the mean value of net fixed assets.
In this case, the ROIC corresponds to the ratio of these two averages.
Fortunately, they're simple to calculate. It's easy to check that the mean net
income is $67,200. Moreover, it's straightforward to show that the mean value of
net fixed assets is $245,000. By dividing the first average by the second one,
we get the following result for the ROIC: 27.42857142857143%. As in Problem 10,
since the number of decimal places to keep isn't clear, we answer this question
with as much precision as we can get.

* Problem 14

*Answer:* Yes\\

In Problem 11, we've computed the NPV. As we've seen, this value is positive.
This suggests it's a good idea to purchase the oven.

# Local Variables:
# ispell-alternate-dictionary: "american"
# End:
