:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+AUTHOR: Marcio Woitek
#+TITLE: Final Exam
#+LATEX_HEADER: \usepackage[a4paper,left=1cm,right=1cm,top=1cm,bottom=1cm]{geometry}
#+LATEX_HEADER: \usepackage[american]{babel}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[sc]{mathpazo}
#+LATEX_HEADER: \linespread{1.05}
#+LATEX_HEADER: \renewcommand{\labelitemi}{$\rhd$}
#+LATEX_HEADER: \setlength\parindent{0pt}
#+LATEX_HEADER: \setlist[itemize]{leftmargin=*}
#+LATEX_HEADER: \setlist{nosep}
#+OPTIONS: ':t
#+OPTIONS: author:nil
#+OPTIONS: date:nil
#+OPTIONS: title:nil
#+OPTIONS: toc:nil
#+STARTUP: hideblocks

#+BEGIN_SRC latex
\thispagestyle{empty}
\pagestyle{empty}
#+END_SRC

* Problem 1

*Answer:* Fall\\

Denote the interest rate by \( r \). To compute the present value, we need to
determine the "discount factor"
\begin{equation*}
\frac{1}{(1+r)^t},
\end{equation*}
where, for this problem, \( t=5 \) years. If the interest rate increases, then
the above factor decreases. As a result, the present value also decreases.

* Problem 2

*Answer:* Row A\\

To decide on the best option, we need to compute the present value for each cash
flow. To do so, we have to discount every amount to determine its present value.
Recall that the discounted amount decreases as time goes by. Then it's better to
receive the largest amounts as soon as possible. This suggests that the best
option corresponds to the cash-inflow in *row A*.

* Problem 3

*Answer:* Decrease it\\

The reasoning behind this answer was explained in the solution to Problem 1. The
only difference is that in this case we want the present value to increase. In
other words, in comparison with the first problem, now we have the opposite
situation. Therefore, for the PV to increase, we need the discount rate to
decrease.

* Problem 4

*Answer:* Cash flow

* Problem 5

*Answer:* Cash creation is a better measure of firm value

* Problem 6

*Answer:* Decreasing FCF by any increase in the level of working capital

* Problem 7

*Answer:* Depreciation is a non-cash expense

* Problem 8

*Answer:* The amount of value left in the project at the end of the forecast

* Problem 9

*Answer:* All the above

* Problem 10

*Answer:* 20%\\

The original price can be seen as a present value: \( \mathrm{PV}=26 \). Then
the selling price is the corresponding future value: \( \mathrm{FV}=45 \). So,
to answer this question, we'll use the formula
\begin{equation}
\mathrm{FV}=\mathrm{PV}(1+r)^t,
\end{equation}
where \( r \) represents the rate of return, and \( t=3 \) years. Since we need
to determine \( r \), let us first solve the above equation for this variable:
\begin{align}
  \begin{split}
    \mathrm{FV}&=\mathrm{PV}(1+r)^t\\
    \frac{\mathrm{FV}}{\mathrm{PV}}&=(1+r)^t\\
    \left(\frac{\mathrm{FV}}{\mathrm{PV}}\right)^{1/t}&=1+r\\
    r&=\left(\frac{\mathrm{FV}}{\mathrm{PV}}\right)^{1/t}-1
  \end{split}
\end{align}
By substituting the known values into the RHS of this equation, we get
#+NAME: problem_10
#+BEGIN_SRC python :results output :exports none
pv = 26
fv = 45
t = 3
r = (fv / pv) ** (1 / t) - 1
print(round(r, 2))
print(f"{round(100 * r, 0)}%")
#+END_SRC
#+RESULTS: problem_10
: 0.2
: 20.0%
\begin{align}
  \begin{split}
    r&=\left(\frac{\mathrm{FV}}{\mathrm{PV}}\right)^{1/t}-1\\
    &=\left(\frac{45}{26}\right)^{1/3}-1\\
    &\approx 0.2.
  \end{split}
\end{align}
Therefore, the annual rate of return is 20%.

* Problem 11

*Answer:* Stock market dividends

* Problem 12

*Answer:* $6,843\\

To answer this question, we need to compute a future value. We begin by
summarizing the information we were given:
- the present value is \( \mathrm{PV}=5000 \);
- the interest rate is \( r=0.04 \);
- the number of time periods is \( t=8 \) years.
Recall that the future value can be written as
\begin{equation}
\mathrm{FV}=\mathrm{PV}(1+r)^t.
\end{equation}
By substituting all the known values into the above equation, we get
#+NAME: problem_12
#+BEGIN_SRC python :results output :exports none
pv = 5000
r = 0.04
t = 8
fv = pv * (1 + r)**t
print(round(fv, 0))
#+END_SRC
#+RESULTS: problem_12
: 6843.0
\begin{equation}
\mathrm{FV}=5000(1+0.04)^8\approx 6843.
\end{equation}
Therefore, the account balance will be approximately $6,843.

* Problem 13

*Answer:* All of the above

* Problem 14

*Answer:* All of the above

* Problem 15

*Answer:* 7.71%\\

#+NAME: problem_15
#+BEGIN_SRC python :results output :exports none
from sympy import Eq, Float, Pow, Symbol, latex, simplify
from sympy.sets.sets import Set
from sympy.solvers.solveset import solveset_real


def irr_equation(initial_investment: int | float, cash_flow: list[int] | list[float]) -> tuple[Eq, Set]:
    irr = Symbol("IRR")
    npv = Float(-initial_investment)
    for t, f in enumerate(cash_flow, start=1):
        npv += Float(f) / Pow(Float(1) + irr, t)
    lhs = npv * Pow(Float(1) + irr, len(cash_flow))
    equation = simplify(Eq(lhs, 0))
    solutions = solveset_real(equation, irr)
    return equation, solutions


initial_investment = 5000
cash_flow = [1500] * 4
eq, sol = irr_equation(initial_investment, cash_flow)
print(latex(eq))
print(sol)
#+END_SRC
#+RESULTS: problem_15
: 5000.0 IRR^{4} + 18500.0 IRR^{3} + 24000.0 IRR^{2} + 11000.0 IRR = 1000.0
: {-1.628058719756, 0.0771384729520836}
In this case, it's possible to show that the \( \mathrm{IRR} \) satisfies the
following quartic equation:
\begin{equation}
5\mathrm{IRR}^4+18.5\mathrm{IRR}^3+24\mathrm{IRR}^2+11\mathrm{IRR}-1=0.
\end{equation}
This equation has two real solutions. However, only one of them is positive.
This root is approximately 0.0771. Therefore, as a percentage, the
\( \mathrm{IRR} \) is approximately 7.71%.

* Problem 16

*Answer:* \( \mathrm{NPV}=\$-245 \); reject the project\\

#+NAME: problem_16
#+BEGIN_SRC python :results output :exports none
from typing import cast


def npv(
    initial_investment: float,
    cash_flow: float | list[float],
    discount_rate: float,
    time_periods: int,
) -> float:
    if not isinstance(cash_flow, list):
        cash_flow = [float(cash_flow)] * time_periods
    cash_flow = cast(list, cash_flow)
    pv_cash_flow = sum(f / (1 + discount_rate) ** t for f, t in zip(cash_flow, range(1, time_periods + 1)))
    return pv_cash_flow - initial_investment


initial_investment = 5000
cash_flow = 1500
discount_rate = 0.1
time_periods = 4

ans = npv(initial_investment, cash_flow, discount_rate, time_periods)
print(round(ans, 2))
#+END_SRC
#+RESULTS: problem_16
: -245.2
I wrote a Python function to compute the net present value. To solve this
problem, I simply used this function. For this reason, I'm not presenting a
detailed explanation of my solution. However, the result for the NPV is
\( -245.2 \). Since this value is negative, the firm should reject this project.

* Problem 17

*Answer:* NPV

* Problem 18

*Answer:* The payback period does not incorporate the time value of money

* Problem 19

*Answer:* All the above

* Problem 20

*Answer:* The minimum rate firms should earn on the equity-financed part of an
investment

* Problem 21

*Answer:* Based on the market beta and the equity risk premium

* Problem 22

*Answer:* More risk that cannot be avoided

* Problem 23

*Answer:* The earning per share for the next time period.

* Problem 24

*Answer:* There is more systematic risk involved for the common stock

* Problem 25

*Answer:* 9.12%\\

We begin by summarizing the information we were given. Denote by \( A \) the
amount in assets. Then we have the following:
- the debt is \( D=0.6 A \);
- the equity is \( E=0.4 A \);
- the cost of debt is \( R_d=0.08 \);
- the cost of equity is \( R_e=0.15 \);
- the tax rate is \( t=0.35 \).
Next, recall that the WACC is given by
\begin{equation}
\mathrm{WACC}=\frac{E}{E+D}R_e+\frac{D}{E+D}(1-t)R_d.
\end{equation}
We know all the values on the RHS of this equation. By substituting these values
into this formula, we get
#+NAME: problem_25
#+BEGIN_SRC python :results output :exports none
wacc = 0.4 * 0.15 + 0.6 * 0.65 * 0.08
print(round(wacc, 4))
print(f"{round(100 * wacc, 2)}%")
#+END_SRC
#+RESULTS: problem_25
: 0.0912
: 9.12%
\begin{align}
  \begin{split}
    \mathrm{WACC}&=\frac{E}{E+D}R_e+\frac{D}{E+D}(1-t)R_d\\
    &=\frac{0.4 A}{0.4 A+0.6 A}\cdot 0.15+\frac{0.6 A}{0.4 A+0.6 A}\cdot(1-0.35)\cdot 0.08\\
    &=0.4\cdot 0.15+0.6\cdot 0.65\cdot 0.08\\
    &=0.0912.
  \end{split}
\end{align}
Therefore, the WACC for this company is 9.12%.

# Local Variables:
# ispell-alternate-dictionary: "american"
# End:
